//=============================================================================
// Andrew_BatchAoEPopupLog.js
//=============================================================================

/*:
 * @plugindesc v5.00 Removes per-target battle-log waits from all-target
 * actions while preserving normal single-target battle-log behavior.
 * Requires YEP_BattleEngineCore.
 * @author Andrew
 *
 * @param Batch Scopes
 * @desc Scope IDs that should have their battle-log waits removed.
 * @default 2,8,10
 *
 * @help
 * ============================================================================
 * Andrew_BatchAoEPopupLog
 * ============================================================================
 *
 * This plugin specifically removes the wait generated by Window_BattleLog's
 * addText() when displaying the results of an all-target action.
 *
 * Default scopes:
 *
 *   2  = All Enemies
 *   8  = All Allies
 *   10 = All Dead Allies
 *
 * Normal single-target actions retain the default battle-log behavior.
 *
 * Damage calculations are unchanged.
 * Damage values are unchanged.
 * Target selection is unchanged.
 *
 * Load this plugin BELOW YEP_BattleEngineCore.
 *
 * ============================================================================
 */

var Imported = Imported || {};
Imported.Andrew_BatchAoEPopupLog = true;

var Andrew = Andrew || {};
Andrew.BatchAoEPopupLog = Andrew.BatchAoEPopupLog || {};
Andrew.BatchAoEPopupLog.version = 5.00;

(function() {

    'use strict';

    var pluginName = 'Andrew_BatchAoEPopupLog';

    //-------------------------------------------------------------------------
    // Parameters
    //-------------------------------------------------------------------------

    var parameters = PluginManager.parameters(pluginName);

    var batchScopes = String(parameters['Batch Scopes'] || '2,8,10')
        .split(',')
        .map(function(value) {
            return parseInt(value.trim(), 10);
        })
        .filter(function(value) {
            return !isNaN(value);
        });

    Andrew.BatchAoEPopupLog.batchScopes = batchScopes;

    //-------------------------------------------------------------------------
    // Determine whether the action currently being processed is a batch scope.
    //-------------------------------------------------------------------------

    Andrew.BatchAoEPopupLog.isBatchAction = function() {

        var action = BattleManager._action;

        if (!action) {
            return false;
        }

        var item = action.item();

        if (!item) {
            return false;
        }

        return batchScopes.indexOf(item.scope) >= 0;
    };

    //-------------------------------------------------------------------------
    // Window_BattleLog.addText
    //
    // This is the important part.
    //
    // Default MV:
    //
    //     this._lines.push(text);
    //     this.refresh();
    //     this.wait();
    //
    // The final this.wait() is what causes the battle log to pause after each
    // target's damage text.
    //
    // For our configured AoE scopes we perform the first two operations but
    // deliberately omit wait().
    //-------------------------------------------------------------------------

    var _Window_BattleLog_addText =
        Window_BattleLog.prototype.addText;

    Window_BattleLog.prototype.addText = function(text) {

        if (Andrew.BatchAoEPopupLog.isBatchAction()) {

            this._lines.push(text);
            this.refresh();

            // IMPORTANT:
            // Do NOT call this.wait() here.
            return;
        }

        _Window_BattleLog_addText.call(this, text);
    };

})();