/*:
 * @plugindesc Skill 380 item selection: opens the battle Item window when Skill 380
 *             resolves, then applies the chosen item to Skill 380's last target.
 * @author Andrew (adapted from LotPItemSelect.js)
 *
 * @help
 * When Skill 380 resolves, this plugin captures the last target the skill hit,
 * pauses the turn, and opens the standard battle Item window so the player can
 * pick a consumable. The chosen item is applied ONLY to that captured target
 * (not the whole party), consumed from inventory, and the turn then resumes.
 * The chosen item is also remembered per-actor so it can be auto-replayed.
 *
 * If skill 380 was cast by Auto-Battle.js's replay logic (actor's weapon is
 * the "Emiraji Blowpipe" and their last used skill was 380), the item window
 * is skipped entirely and the actor's last-used item is auto-applied to the
 * same last target instead — no re-prompting the player.
 *
 * Ported from LotPItemSelect.js (skill-detect hook, token-gated endAction
 * pause, Window_BattleItem OK/cancel intercepts, and the Auto-Battle
 * lastItem auto-apply branch). One thing present in that plugin was
 * intentionally left out here since it was specific to skill 58 and wasn't
 * asked for: state 28 cleanup (skill 58's scope-changing state). That can be
 * added back the same way if skill 380 turns out to need an equivalent.
 */

(function() {
  const SKILL_ID = 380;

  // State for the pending flow
  let pendingItemUse = false;
  let skillItemActive = false;
  let autoModePending = false;
  let actingActor = null;
  let lastTarget = null;

  // Token to tie a pending item-select flow to one specific action instance
  let pendingItemUseToken = 0;
  let activePendingToken = 0;

  function getActionSubject(action) {
    return (action && action.subject && action.subject()) || (BattleManager.actor && BattleManager.actor()) || BattleManager._subject || null;
  }

  // Detect whether this Game_Action instance was generated by
  // Auto-Battle.js's makeAutoBattleActions (tagged _isAutoBattleAction).
  function isAutoBattleAction(action) {
    return !!(action && action._isAutoBattleAction);
  }

  // Per-actor "last item used with skill 380", stored on $gameSystem so it
  // survives save/load like LotPItemSelect.js's equivalent storage.
  function getActorLastSkill380Item(actor) {
    if (!actor) return null;
    try {
      if ($gameSystem && $gameSystem._skill380LastItems) {
        const itemId = $gameSystem._skill380LastItems[actor.actorId()];
        if (itemId && $dataItems[itemId] && $gameParty.numItems($dataItems[itemId]) > 0) {
          return $dataItems[itemId];
        }
      }
    } catch (e) {
      if (typeof console !== 'undefined') console.warn("Skill380ItemSelect: getActorLastSkill380Item error:", e);
    }
    return null;
  }

  function recordActorLastSkill380Item(actor, item) {
    try {
      if (!actor || !item) return;
      $gameSystem._skill380LastItems = $gameSystem._skill380LastItems || {};
      $gameSystem._skill380LastItems[actor.actorId()] = item.id;
    } catch (e) {
      if (typeof console !== 'undefined') console.warn("Skill380ItemSelect: recordActorLastSkill380Item error:", e);
    }
  }

  // --- Detect Skill 380 and capture its last target ---
  const _Game_Action_apply = Game_Action.prototype.apply;
  Game_Action.prototype.apply = function(target) {
    _Game_Action_apply.call(this, target);
    try {
      const item = this.item && this.item();
      if (!item || item.id !== SKILL_ID) return;

      actingActor = getActionSubject(this);
      lastTarget = target; // overwritten on each hit, so the final call wins
      autoModePending = isAutoBattleAction(this);

      pendingItemUse = true;
      pendingItemUseToken = (pendingItemUseToken + 1) & 0x7fffffff;
      activePendingToken = pendingItemUseToken;

      if (typeof console !== 'undefined') {
        console.log("Skill380ItemSelect: skill 380 detected for", actingActor ? actingActor.name() : "NULL",
          "target:", target ? target.name() : "NULL", "auto:", autoModePending, "token:", activePendingToken);
      }
    } catch (e) {
      if (typeof console !== 'undefined') console.error("Skill380ItemSelect Game_Action.apply error:", e);
    }
  };

  // --- End action: open the item window for the pending Skill 380 cast ---
  const _BattleManager_endAction = BattleManager.endAction;
  BattleManager.endAction = function() {
    if (pendingItemUse) {
      const myToken = activePendingToken;
      pendingItemUse = false;

      // Token mismatch means another action started since; skip our handling
      if (myToken === 0 || myToken !== pendingItemUseToken) {
        activePendingToken = 0;
        autoModePending = false;
        _BattleManager_endAction.call(this);
        return;
      }

      // Auto-Battle replay: skip the interactive window entirely and
      // auto-apply the actor's last-used item to the same last target.
      if (autoModePending) {
        autoModePending = false;
        try {
          const lastItem = getActorLastSkill380Item(actingActor);
          if (lastItem) {
            if (typeof console !== 'undefined') console.log("Skill380ItemSelect: auto-mode applying", lastItem.name, "for", actingActor ? actingActor.name() : "NULL");
            applySelectedItem(lastItem);
          } else {
            if (typeof console !== 'undefined') console.warn("Skill380ItemSelect: auto-mode has no usable last item for", actingActor ? actingActor.name() : "NULL", "- skipping item effect.");
            actingActor = null;
            lastTarget = null;
          }
        } catch (e) {
          if (typeof console !== 'undefined') console.error("Skill380ItemSelect: auto-mode item apply error:", e);
        }
        activePendingToken = 0;
        _BattleManager_endAction.call(this);
        return;
      }

      try {
        const scene = SceneManager._scene;
        if (scene && typeof scene.commandItem === 'function') {
          skillItemActive = true;
          scene.commandItem();
          // do not clear activePendingToken here; it's cleared after selection
          return; // wait for player selection
        }
        if (typeof console !== 'undefined') console.warn("Skill380ItemSelect: commandItem unavailable; completing action to avoid stall.");
      } catch (e) {
        if (typeof console !== 'undefined') console.error("Skill380ItemSelect: error opening item menu:", e);
      }
      activePendingToken = 0;
      _BattleManager_endAction.call(this);
      return;
    }

    _BattleManager_endAction.call(this);
  };

  // --- Intercept OK on the item window while our flow is active ---
  const _Window_BattleItem_callOkHandler = Window_BattleItem.prototype.callOkHandler;
  Window_BattleItem.prototype.callOkHandler = function() {
    if (skillItemActive) {
      const selectedItem = this.item();
      if (!selectedItem) {
        SoundManager.playBuzzer();
        return;
      }
      recordActorLastSkill380Item(actingActor, selectedItem);
      applySelectedItem(selectedItem);
      skillItemActive = false;
      activePendingToken = 0;
      this.hide();
      return;
    }
    _Window_BattleItem_callOkHandler.call(this);
  };

  // --- Disable cancel while our flow is active (a target must be chosen) ---
  const _Window_BattleItem_processCancel = Window_BattleItem.prototype.processCancel;
  Window_BattleItem.prototype.processCancel = function() {
    if (skillItemActive) {
      SoundManager.playBuzzer();
      return;
    }
    _Window_BattleItem_processCancel.call(this);
  };

  const _Window_BattleItem_callCancelHandler = Window_BattleItem.prototype.callCancelHandler;
  Window_BattleItem.prototype.callCancelHandler = function() {
    if (skillItemActive) {
      SoundManager.playBuzzer();
      return;
    }
    _Window_BattleItem_callCancelHandler.call(this);
  };

  const _Window_BattleItem_cancel = Window_BattleItem.prototype.cancel;
  Window_BattleItem.prototype.cancel = function() {
    if (skillItemActive) {
      SoundManager.playBuzzer();
      return;
    }
    _Window_BattleItem_cancel.call(this);
  };

  // --- Apply the selected item to Skill 380's last target only ---
  function applySelectedItem(item) {
    try {
      if (!actingActor) {
        if (typeof console !== 'undefined') console.error("Skill380ItemSelect: actingActor is null.");
        return;
      }
      if (!lastTarget || typeof lastTarget.isAlive !== 'function' || !lastTarget.isAlive()) {
        if (typeof console !== 'undefined') console.warn("Skill380ItemSelect: no valid last target for skill 380; item not used.");
        return;
      }
      if ($gameParty.numItems(item) <= 0) {
        if (typeof console !== 'undefined') console.error("Skill380ItemSelect: party has no copies of", item.name);
        return;
      }

      const action = new Game_Action(actingActor);
      action.setItem(item.id);
      // Prevent an Auto-Battle "last action" recorder from mistaking this
      // internal item cast for the actor's committed action, if such a
      // plugin is present (mirrors LotPItemSelect.js's convention).
      action._skipAutoBattleRecord = true;
      action.apply(lastTarget);

      $gameParty.consumeItem(item);

      if (typeof console !== 'undefined') {
        console.log("Skill380ItemSelect: applied", item.name, "from", actingActor.name(), "to", lastTarget.name());
      }
    } catch (e) {
      if (typeof console !== 'undefined') console.error("Skill380ItemSelect applySelectedItem error:", e);
    } finally {
      actingActor = null;
      lastTarget = null;
      skillItemActive = false;
      autoModePending = false;
      activePendingToken = 0;
    }
  }

})();